# Generated by Django 4.2.20 on 2025-07-09 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chauffeur',
            fields=[
                ('id_chauffeur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_chauffeur', models.CharField(max_length=50)),
                ('prenom_chauffeur', models.CharField(max_length=50)),
                ('permis_chauffeur', models.CharField(max_length=20, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
            ],
        ),
        migrations.CreateModel(
            name='camion',
            fields=[
                ('id_camion', models.AutoField(primary_key=True, serialize=False)),
                ('matricule_camion', models.CharField(max_length=20, unique=True)),
                ('nom_societe', models.CharField(max_length=100)),
                ('capacite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_entreeC', models.DateField()),
                ('date_sortieC', models.DateField()),
                ('heure_entreeC', models.TimeField()),
                ('heure_sortieC', models.TimeField()),
                ('id_chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.chauffeur')),
            ],
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.camion')),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.chauffeur')),
            ],
        ),
    ]
