# Generated by Django 4.2.20 on 2025-07-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='date_sortieC',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='camion',
            name='heure_sortieC',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
