# Generated by Django 4.2.20 on 2025-07-10 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_camion_date_sortiec_alter_camion_heure_sortiec'),
    ]

    operations = [
        migrations.CreateModel(
            name='prestataire',
            fields=[
                ('id_prestataire', models.AutoField(primary_key=True, serialize=False)),
                ('nom_prestataire', models.CharField(max_length=100)),
                ('adresse_prestataire', models.CharField(max_length=255)),
                ('frais_prestataire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('telephone_prestataire', models.CharField(max_length=15, unique=True)),
                ('matricule_camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.camion')),
            ],
        ),
    ]
