# Generated by Django 4.2.20 on 2025-07-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_prestataire'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
