# Generated by Django 4.2.20 on 2025-07-10 15:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_prestataire_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestataire',
            name='matricule_camion',
        ),
        migrations.AddField(
            model_name='affectation',
            name='date_debut',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='affectation',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='prestataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.prestataire'),
        ),
    ]
