# Generated by Django 4.2.20 on 2025-07-14 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_prestataire_matricule_camion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camion',
            old_name='id_chauffeur',
            new_name='chauffeur',
        ),
    ]
