# Generated by Django 4.2.20 on 2025-07-14 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_id_chauffeur_camion_chauffeur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camion',
            old_name='chauffeur',
            new_name='id_chauffeur',
        ),
    ]
