# Generated by Django 4.2.20 on 2025-07-14 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_chauffeur_camion_id_chauffeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='id_prestataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.prestataire'),
        ),
    ]
