# Generated by Django 4.2.20 on 2025-07-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_camion_id_prestataire'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
