# Generated by Django 4.2.20 on 2025-07-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_camion_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camion',
            name='qr_code',
        ),
    ]
