# Generated by Django 4.2.20 on 2025-07-14 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_camion_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affectation',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='affectation',
            name='date_fin',
        ),
        migrations.AddField(
            model_name='affectation',
            name='prestataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.prestataire'),
        ),
        migrations.AddField(
            model_name='affectation',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
