# Generated by Django 4.2.20 on 2025-07-14 14:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_affectation_date_debut_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affectation',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Affectation', 'verbose_name_plural': 'Affectations'},
        ),
        migrations.AddField(
            model_name='affectation',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 14, 15, 31, 45, 536897), verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affectation',
            name='camion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affectation', to='app.camion', verbose_name='Camion'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='chauffeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.chauffeur', verbose_name='Chauffeur'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='prestataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.prestataire', verbose_name='Prestataire'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/affectations/', verbose_name='QR Code'),
        ),
    ]
