# Generated by Django 4.2.20 on 2025-07-14 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_affectation_options_affectation_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affectation',
            options={},
        ),
        migrations.RemoveField(
            model_name='affectation',
            name='date_creation',
        ),
        migrations.AlterField(
            model_name='affectation',
            name='camion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.camion'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='chauffeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.chauffeur'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='prestataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.prestataire'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
