# Generated by Django 4.2.20 on 2025-07-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_affectation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
