# Generated by Django 4.2.20 on 2025-07-18 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camion',
            name='date_entreeC',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='date_sortieC',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='heure_entreeC',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='heure_sortieC',
        ),
        migrations.CreateModel(
            name='EntreeSortie',
            fields=[
                ('id_entreeSortie', models.AutoField(primary_key=True, serialize=False)),
                ('date_entree', models.DateField()),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('heure_entree', models.TimeField()),
                ('heure_sortie', models.TimeField(blank=True, null=True)),
                ('affectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.affectation')),
            ],
        ),
    ]
