# Generated by Django 4.2.20 on 2025-07-18 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_camion_date_entreec_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camion',
            name='nom_societe',
        ),
    ]
