# Generated by Django 4.2.20 on 2025-07-25 10:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_camion_nom_societe'),
    ]

    operations = [
        migrations.CreateModel(
            name='site',
            fields=[
                ('id_site', models.AutoField(primary_key=True, serialize=False)),
                ('nom_site', models.CharField(max_length=150)),
                ('adresse_site', models.CharField(max_length=150)),
                ('telephone_site', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id_facture', models.AutoField(primary_key=True, serialize=False)),
                ('poids_marchandise', models.FloatField(help_text='Poids en tonnes', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('destination', models.CharField(max_length=200)),
                ('latitude_depart', models.FloatField(blank=True, help_text='Laisser vide pour utiliser la position GPS actuelle', null=True)),
                ('longitude_depart', models.FloatField(blank=True, help_text='Laisser vide pour utiliser la position GPS actuelle', null=True)),
                ('latitude_destination', models.FloatField(blank=True, help_text="Rempli automatiquement à partir de l'adresse de destination", null=True)),
                ('longitude_destination', models.FloatField(blank=True, help_text="Rempli automatiquement à partir de l'adresse de destination", null=True)),
                ('distance_km', models.FloatField(blank=True, default=0, help_text='Distance en kilomètres, calculée automatiquement', null=True)),
                ('frais_marchandise', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('prix_par_km', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('prix_par_tonne', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_facture', models.DateField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('affectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='app.affectation')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_facture'],
            },
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.site'),
        ),
    ]
